from core.comp.dataset_readers.readers import ImpBaseDatasetReader, ImpFlatCombinedAlignDatasetReader
from core.comp.nn.fusion.diff_siso_fusions.diff_siso_op_mask_fusion_fix import DiffSiSoOpMaskJointConcatAttentionFixFusion
from core.comp.nn.fusion.diff_siso_fusions.diff_siso_fusion_wrapper import DiffSiSoOpMaskFLAHybridFusion
from core.comp.nn.fusion.diff_siso_fusions.diff_siso_line_align_fusion import DiffSiSoFLAFusion
from core.comp.nn.fusion.sivo_fusions.sivo_joint_attn_flat_fusion import SiVoOpMaskJointConcatAttentionFusion
from core.comp.nn.fusion.sivo_fusions.sivo_joint_attn_line_align_fusion import SiVoFlatLineAlignJointConcatAttentionFusion
from core.comp.metric.bleu_norm import BNorm
from core.models.classification.hybrid_imp_seqin_classifier import ImpClassifier
from core.models.seq2seq.hybird_cc_simple_seq2seq import HybridCcSimpleSeq2Seq
from core.models.seq2seq.hybrid_cc_modular_seq2seq import HybridCcModularSeq2Seq
from core.comp.callbacks import *